// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhlyatwlvuxdivrjqcpb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJobHlhdHdsdnV4ZGl2cmpxY3BiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NDIxMjEsImV4cCI6MjA2OTExODEyMX0.GCe6AdwUxAnBKImN7kLD2YIdmRm6JZMRHOJO4z0oKso";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});